earth_sun: earth_sun.cpp
	g++ earth_sun.cpp -o earth_sun

earth_mars_sun: earth_mars_sun.cpp
	g++ earth_mars_sun.cpp -o earth_mars_sun

solar_system: solar_system.cpp
	g++ solar_system.cpp -o solar_system